workflows:
  android-workflow:
    name: Build Android APK & AAB - Supermarché App
    max_build_duration: 60

    # Suppression de instance_type (inutile pour Android seul)
    # Suppression de xcode/cocoapods (non nécessaires)

    environment:
      flutter: 3.24.0  # Version stable récente, compatible avec tes plugins
      groups:
        - default
      vars:
        JAVA_HOME: /usr/lib/jvm/zulu17-ca-amd64  # Chemin standard sur builder Linux

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle

    scripts:
      - name: 🧩 Configuration de local.properties avec AndroidX
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "flutter.sdk=$FLUTTER_ROOT" >> "$CM_BUILD_DIR/android/local.properties"
          echo "android.useAndroidX=true" >> "$CM_BUILD_DIR/android/local.properties"
          echo "android.enableJetifier=true" >> "$CM_BUILD_DIR/android/local.properties"
          echo "✅ local.properties configuré avec AndroidX"

      - name: 🧹 Nettoyage initial
        script: |
          flutter clean
          rm -rf android/.gradle  # Évite les caches Gradle corrompus

      - name: 📦 Récupération des dépendances
        script: |
          flutter pub get
          echo "✅ Dépendances installées"

      - name: 🔍 Analyse du code (non bloquant)
        script: |
          flutter analyze || echo "⚠️ Analyse terminée (avertissements ignorés)"

      - name: 🚀 Construction de l'APK Release
        script: |
          flutter build apk --release --no-tree-shake-icons
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "❌ Échec : APK non généré"
            exit 1
          fi
          echo "✅ APK Release prêt"

      - name: 🏗️ Construction du Bundle AAB
        script: |
          flutter build appbundle --release --no-tree-shake-icons
          if [ ! -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "❌ Échec : AAB non généré"
            exit 1
          fi
          echo "✅ AAB Release prêt"

      - name: 🧾 Informations de build
        script: |
          cat > build_info.txt << EOF
========================================
BUILD INFORMATION - Supermarché App
========================================
Date : $(date '+%Y-%m-%d %H:%M:%S')
Flutter : $(flutter --version | head -n1)
Commit : $CM_COMMIT
Branche : $CM_BRANCH
========================================
EOF
          cat build_info.txt

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build_info.txt

    publishing:
      email:
        recipients:
          - niame225@gmail.com
        notify:
          success: true
          failure: true
        message: |
          🚀 Le build Android de *Supermarché App* est terminé !
          📦 Fichiers APK/AAB disponibles dans les artifacts.