workflows:
  android-workflow:
    name: Build Android APK & AAB - Supermarché App
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: 3.19.0
      xcode: latest
      cocoapods: default
      groups:
        - default
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle

    scripts:
      - name: 🧩 Configuration de local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "✅ Fichier local.properties créé avec succès"

      - name: 📦 Récupération des dépendances Flutter
        script: |
          flutter clean
          flutter pub get
          echo "✅ Dépendances téléchargées avec succès"

      - name: 🔍 Analyse du code Flutter
        script: |
          set -e
          flutter analyze || echo "⚠️ Avertissements détectés (non bloquants)"

      - name: 🚀 Construction de l'APK Release
        script: |
          echo "📦 Construction de l'APK Release..."
          flutter build apk --release --verbose

          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "❌ ERREUR: APK release non créé !"
            exit 1
          fi
          echo "✅ APK Release créé avec succès"

      - name: 🏗️ Construction du Bundle AAB
        script: |
          echo "📦 Construction du Bundle AAB..."
          flutter build appbundle --release --verbose

          if [ ! -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "❌ ERREUR: AAB release non créé !"
            exit 1
          fi
          echo "✅ AAB Release créé avec succès"

      - name: 🧾 Génération des informations de build
        script: |
          cat > build_info.txt << EOF
          ========================================
          BUILD INFORMATION - Supermarché App
          ========================================
          Date de build : $(date '+%Y-%m-%d %H:%M:%S')
          Flutter Version : $(flutter --version | head -n 1)
          Android SDK : $ANDROID_SDK_ROOT
          Commit : $CM_COMMIT
          Branche : $CM_BRANCH
          ========================================
          EOF
          cat build_info.txt

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build_info.txt

    publishing:
      email:
        recipients:
          - niame225@gmail.com
        notify:
          success: true
          failure: true
        message: |
          🚀 Le build Android de *Supermarché App* s'est terminé avec succès !
          📦 Les fichiers APK et AAB sont disponibles dans les artifacts Codemagic.
