workflows:
  android-workflow:
    name: Build Android APK & AAB - Supermarché App
    max_build_duration: 60
    environment:
      flutter: 3.24.0
      groups:
        - default
      vars:
        JAVA_HOME: /usr/lib/jvm/zulu17-ca-amd64
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle
    scripts:
      - name: Configuration de local.properties avec AndroidX
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          echo "flutter.sdk=$FLUTTER_ROOT" >> "$CM_BUILD_DIR/android/local.properties"
          echo "android.useAndroidX=true" >> "$CM_BUILD_DIR/android/local.properties"
          echo "android.enableJetifier=true" >> "$CM_BUILD_DIR/android/local.properties"
          echo "local.properties configured"
      - name: Nettoyage initial
        script: |
          flutter clean
          rm -rf android/.gradle
      - name: Récupération des dépendances
        script: |
          flutter pub get
          echo "Dependencies installed"
      - name: Analyse du code
        script: |
          flutter analyze || echo "Analysis completed"
      - name: Construction de l'APK Release
        script: |
          flutter build apk --release --no-tree-shake-icons
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "APK build failed"
            exit 1
          fi
          echo "APK Release ready"
      - name: Construction du Bundle AAB
        script: |
          flutter build appbundle --release --no-tree-shake-icons
          if [ ! -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "AAB build failed"
            exit 1
          fi
          echo "AAB Release ready"
      - name: Informations de build
        script: |
          cat > build_info.txt << 'EOF'
          ========================================
          BUILD INFORMATION - Supermarche App
          ========================================
          EOF
          echo "Date: $(date '+%Y-%m-%d %H:%M:%S')" >> build_info.txt
          echo "Flutter: $(flutter --version | head -n1)" >> build_info.txt
          echo "Commit: $CM_COMMIT" >> build_info.txt
          echo "Branch: $CM_BRANCH" >> build_info.txt
          echo "========================================" >> build_info.txt
          cat build_info.txt
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
      - build_info.txt
    publishing:
      email:
        recipients:
          - niame225@gmail.com
        notify:
          success: true
          failure: true