name: Build Android APK & AAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permet de lancer manuellement depuis GitHub

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses > /dev/null 2>&1 || true

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Build AAB (release)
        run: flutter build appbundle --release

      - name: Generate build info file
        run: |
          echo "Build Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > build_info.txt
          echo "Flutter Version: $(flutter --version | head -n1)" >> build_info.txt
          echo "Commit Hash: ${{ github.sha }}" >> build_info.txt
          echo "Branch: ${{ github.ref_name }}" >> build_info.txt

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build_info.txt
          path: build_info.txt